const header=document.getElementById('siteHeader');window.addEventListener('scroll',()=>header&&header.classList.toggle('scrolled',window.scrollY>20));
const slides=[...document.querySelectorAll('.hero-slide')],dots=[...document.querySelectorAll('.slider-dots button')];let current=0;function showSlide(i){current=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('active',n===current));dots.forEach((d,n)=>d.classList.toggle('active',n===current))}document.querySelector('.next')?.addEventListener('click',()=>showSlide(current+1));document.querySelector('.prev')?.addEventListener('click',()=>showSlide(current-1));dots.forEach((d,i)=>d.addEventListener('click',()=>showSlide(i)));setInterval(()=>showSlide(current+1),6500);
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id&&id.length>1&&id!=='#register'){const el=document.querySelector(id);if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth'});}}}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');if(entry.target.classList.contains('stats-grid')) animateCounters();observer.unobserve(entry.target)}}),{threshold:.16});document.querySelectorAll('.reveal,.reveal-group,.stats-grid').forEach(el=>observer.observe(el));
let counted=false;function animateCounters(){if(counted)return;counted=true;document.querySelectorAll('[data-count]').forEach((el,index)=>{const end=Number(el.dataset.count),plus=el.dataset.plus!=='false',duration=1700;let startTime;setTimeout(()=>{const tick=time=>{startTime??=time;const progress=Math.min((time-startTime)/duration,1),eased=1-Math.pow(1-progress,3),value=Math.floor(eased*end);el.textContent=(progress<1?value:end)+(plus?'+':'');el.classList.add('counting');setTimeout(()=>el.classList.remove('counting'),120);if(progress<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)},index*120)})}
document.querySelectorAll('.faq button').forEach(btn=>btn.addEventListener('click',()=>btn.parentElement.classList.toggle('open')));
document.querySelector('.callback-form')?.addEventListener('submit',e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');const old=btn.textContent;btn.textContent='Request Sent';setTimeout(()=>btn.textContent=old,1800);e.currentTarget.reset();});

document.querySelectorAll('.register-form textarea[data-min]').forEach(area=>area.addEventListener('input',()=>{const count=area.value.trim().split(/\s+/).filter(Boolean).length,min=Number(area.dataset.min),max=Number(area.dataset.max),label=area.nextElementSibling;label.textContent=`Minimum words allowed: ${min}. Total words: ${count}`;label.classList.toggle('invalid',count<min||count>max)}));
document.querySelector('.register-form')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(form.website?.value)return;let valid=true;form.querySelectorAll('textarea[data-min]').forEach(area=>{const count=area.value.trim().split(/\s+/).filter(Boolean).length,min=Number(area.dataset.min),max=Number(area.dataset.max);if(count<min||count>max){valid=false;area.nextElementSibling.classList.add('invalid')}});if(!valid){alert('Please complete all word-limit fields before submitting.');return}const btn=form.querySelector('button');const old=btn.textContent;btn.textContent='Application Submitted';setTimeout(()=>btn.textContent=old,2200);form.reset();form.querySelectorAll('.word-count').forEach(label=>{const area=label.previousElementSibling;label.textContent=`Minimum words allowed: ${area.dataset.min}. Total words: 0`;label.classList.remove('invalid')})});

const registerModal=document.getElementById('register');
function openRegisterModal(){registerModal?.classList.add('open');registerModal?.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeRegisterModal(){registerModal?.classList.remove('open');registerModal?.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
document.querySelectorAll('a[href="#register"]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();openRegisterModal()}));
document.querySelector('.modal-close')?.addEventListener('click',closeRegisterModal);
registerModal?.addEventListener('click',e=>{if(e.target===registerModal)closeRegisterModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeRegisterModal()});
